language: minimal
services:
- docker
addons:
  sonarcloud:
    organization: fred78290-github
    token:
      secure: "OvlXt0mQsBp4qaCT2xdNzyi2lGX/xbuQPu4qK5uTE9eRuo0BOEO/gSl09nX6TQO/zasvx83WU/aeo1RTvjWY0MfQF2WbXlfhXxSNyPQKrP6s0Wpi4HkmUWEkuyHa7u+st/vM4y4+jtWEolhphtfZ3fb8kpYjzhY0FyZZOzoTNn3m8yfowEc4Gthl0Vydk3UNUWdjSy6AsMYtBM6UQofauJtH1/vURXCF/GPKHBwPilLXbvr9B5JbjPP33pTadr8VIPcA29GDR5c0zHZWIgCZFHG5ndPEjNR/HJ2qwOrs1UykiscgpQupbDtRbKEugkIneqLehjiw3e74OZ0vuZOr2vH+H/zRKGMOwX5slfvthC7M/ynwXl4uFNhyEsha/E87r4RRrbFbCHqEGsDaHbii702TI1z1oh/u1gkkipqx1sw6KiVvML4sz/8IxdX4OmTDs3/RhwxioCQYTk/558xlbXr8T6CR5xjEglX6vYLhSSVY+czEfbgLmd3SdSOAelBxuIT/d7gOamoGz/ul4walf2bQ1PFj8ps3zzSSEn+nVH2jYnpwHiSCRvwk2HqY7nwgXjA8FslRehMaGWu9Ic+dO1ZRZvrkF9a7raUKYW4mdHxjKx4HlkK81kRbkm3mpc0ZMOZNSCKzYtPwiP5vPlm2m+IePGgympB9wRFl03MT45g="
cache:
  directories:
    - $HOME/.sonar/cache
    - vendor
jobs:
  include:
    - stage: build
      services: docker
      install: true
      script:
        - make -e REGISTRY=fred78290 -e TAG=dev container
        - sonar-scanner
    - stage: test
      services: docker
      install: true
      script: make test-in-docker
    - stage: deploy
      if: tag IS present OR commit_message =~ /\/ci-deploy/
      services: docker
      install: true
      script: make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_deploy:
        - docker push fred78290/kubernetes-svc-dependencies:$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: Fred78290/kubernetes-svc-dependencies
        file:
        - out/kubernetes-svc-dependencies-darwin-amd64
        - out/kubernetes-svc-dependencies-linux-amd64
