language: minimal
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container
after_deploy:
  - docker push fred78290/kubernetes-svc-dependencies:$TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  on:
    tags: true
    repo: Fred78290/kubernetes-svc-dependencies
  file:
  - out/kubernetes-svc-dependencies-darwin-amd64
  - out/kubernetes-svc-dependencies-linux-amd64