language: minimal
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - make -e REGISTRY=fred78290 -e TAG=v1.13.3 container
before_deploy:
  - docker push fred78290/kubernetes-svc-dependencies:v1.13.3
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  on:
    tags: true
    repo: Fred78290/kubernetes-svc-dependencies
  file:
  - out/kubernetes-svc-dependencies-darwin-amd64
  - out/kubernetes-svc-dependencies-linux-amd64