# Use the newer Travis-CI build templates based on the
# Debian Linux distribution "Bionic" release.
os: linux
dist: bionic
language: minimal
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
addons:
  sonarcloud:
    organization: fred78290-github
    token:
      secure: "HhzcM3fOt1YZqE5xUjYOOjOSGqMZTD5J8N85Sc3SnHPTvIRiC3rBQ1aLOCd2xQZqgugz5CudrK+wRuY/rIYoEcbcod7eJe4TXhTJcaDIawUBYfe5A0ES0jJ9wkaccaUKxBEPIgpEAdzTnB1uPiO3H4Cuf1TH5EKQJFaxOGbgdJ+0sH/FjsLwZSohEdkkCc1no91rOtC/Kmg7wLTMvX7B7x8+KrSouemXsweonfGeI9ueF+coLMKr57AW9evYFYUR/MzIci/dkcGUBwEWJma9delQ+YNlZh6aYsRcAyIyYO0gKRHDHegOdi5pGnYpKXSFga+uKOq/GrcD8KeJUd6QMNj+N9N3GuHUwDRQajqUmSZ0Hb7rNnuSAJ8dEV8lYL6OYz9ZoMPIBS9eZZ3P0pJ1wDVjjZmr5Zb0g6qiFOTB/mVL0UWZ2V13U7IywqaZy0YjL2wPBLr5XHlPBK+EWMLmXo/HJk+VvMEARfpJUfhNrfJ9lTIeah7Sbm0iCLgfaH3sCXvFtQ21vfFhl1nGiYVTzAM/TGdKD7IafhYc8m7gBTxzpodaAZobouYURJRIV5iTzKqQLJkfrL5WBH3hTqNsBMpsS+FhZMycEqlYUKrrBe0REmbfcc5q+LtqKi4q2By5JuvQR7y+8AcAm2nr6RKs3AEoEw6HcWfQdKJl5uNIduU="
cache:
  directories:
    - $HOME/.sonar/cache
    - vendor
jobs:
  include:
    - stage: build
      services: docker
      install: true
      script:
        - sonar-scanner
        - make -e REGISTRY=fred78290 -e TAG=dev container
    - stage: test
      services: docker
      install: true
      script: make test-in-docker
    - stage: deploy
      if: tag IS present OR commit_message =~ /\/ci-deploy/
      services: docker
      install: true
      script: make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_deploy:
        - docker push fred78290/kubernetes-svc-dependencies-amd64:$TRAVIS_TAG
        - docker push fred78290/kubernetes-svc-dependencies-arm64:$TRAVIS_TAG
        - docker manifest create fred78290/kubernetes-svc-dependencies:$TRAVIS_TAG --amend fred78290/kubernetes-svc-dependencies-amd64:$TRAVIS_TAG --amend fred78290/kubernetes-svc-dependencies-arm64:$TRAVIS_TAG
        - docker manifest push fred78290/kubernetes-svc-dependencies:$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: Fred78290/kubernetes-svc-dependencies
        file:
        - out/kubernetes-svc-dependencies-amd64
        - out/kubernetes-svc-dependencies-arm64
